import type { Lesson } from '@/types';

/**
 * A curated list of piano lessons including international classics and Hindi rhymes.
 * All lessons are extended to be at least 10 seconds long.
 */
export const LESSONS: Lesson[] = [
  {
    id: 'twinkle-twinkle-little-star',
    title: 'Twinkle Twinkle',
    instrument: 'piano',
    difficulty: 'Beginner',
    tempo: 100,
    imageId: 'lesson-twinkle-twinkle',
    notes: [
      { key: 'C4', duration: '4n', time: '0:0:0' },
      { key: 'C4', duration: '4n', time: '0:1:0' },
      { key: 'G4', duration: '4n', time: '0:2:0' },
      { key: 'G4', duration: '4n', time: '0:3:0' },
      { key: 'A4', duration: '4n', time: '1:0:0' },
      { key: 'A4', duration: '4n', time: '1:1:0' },
      { key: 'G4', duration: '2n', time: '1:2:0' },
      { key: 'F4', duration: '4n', time: '2:0:0' },
      { key: 'F4', duration: '4n', time: '2:1:0' },
      { key: 'E4', duration: '4n', time: '2:2:0' },
      { key: 'E4', duration: '4n', time: '2:3:0' },
      { key: 'D4', duration: '4n', time: '3:0:0' },
      { key: 'D4', duration: '4n', time: '3:1:0' },
      { key: 'C4', duration: '2n', time: '3:2:0' },
      { key: 'G4', duration: '4n', time: '4:0:0' },
      { key: 'G4', duration: '4n', time: '4:1:0' },
      { key: 'F4', duration: '4n', time: '4:2:0' },
      { key: 'F4', duration: '4n', time: '4:3:0' },
      { key: 'E4', duration: '4n', time: '5:0:0' },
      { key: 'E4', duration: '4n', time: '5:1:0' },
      { key: 'D4', duration: '2n', time: '5:2:0' },
    ],
  },
  {
    id: 'lakdi-ki-kathi',
    title: 'Lakdi Ki Kathi',
    instrument: 'piano',
    difficulty: 'Intermediate',
    tempo: 120,
    imageId: 'lesson-lakdi-kathi',
    notes: [
      { key: 'C4', duration: '8n', time: '0:0:0' },
      { key: 'C4', duration: '8n', time: '0:0:2' },
      { key: 'D4', duration: '8n', time: '0:1:0' },
      { key: 'E4', duration: '8n', time: '0:1:2' },
      { key: 'C4', duration: '4n', time: '0:2:0' },
      { key: 'G4', duration: '8n', time: '0:3:0' },
      { key: 'G4', duration: '8n', time: '0:3:2' },
      { key: 'F4', duration: '8n', time: '1:0:0' },
      { key: 'E4', duration: '8n', time: '1:0:2' },
      { key: 'D4', duration: '4n', time: '1:1:0' },
      { key: 'C4', duration: '8n', time: '2:0:0' },
      { key: 'C4', duration: '8n', time: '2:0:2' },
      { key: 'D4', duration: '8n', time: '2:1:0' },
      { key: 'E4', duration: '8n', time: '2:1:2' },
      { key: 'C4', duration: '4n', time: '2:2:0' },
      { key: 'G4', duration: '8n', time: '2:3:0' },
      { key: 'G4', duration: '8n', time: '2:3:2' },
      { key: 'F4', duration: '8n', time: '3:0:0' },
      { key: 'E4', duration: '8n', time: '3:0:2' },
      { key: 'D4', duration: '4n', time: '3:1:0' },
      { key: 'G4', duration: '4n', time: '4:0:0' },
      { key: 'G4', duration: '4n', time: '4:1:0' },
      { key: 'A4', duration: '4n', time: '4:2:0' },
      { key: 'G4', duration: '4n', time: '4:3:0' },
      { key: 'F4', duration: '4n', time: '5:0:0' },
      { key: 'E4', duration: '4n', time: '5:1:0' },
      { key: 'D4', duration: '2n', time: '5:2:0' },
    ],
  },
  {
    id: 'nani-teri-morni',
    title: 'Nani Teri Morni',
    instrument: 'piano',
    difficulty: 'Beginner',
    tempo: 110,
    imageId: 'lesson-nani-morni',
    notes: [
      { key: 'G4', duration: '4n', time: '0:0:0' },
      { key: 'G4', duration: '4n', time: '0:1:0' },
      { key: 'A4', duration: '8n', time: '0:2:0' },
      { key: 'G4', duration: '8n', time: '0:2:2' },
      { key: 'F4', duration: '4n', time: '0:3:0' },
      { key: 'E4', duration: '4n', time: '1:0:0' },
      { key: 'D4', duration: '4n', time: '1:1:0' },
      { key: 'C4', duration: '2n', time: '1:2:0' },
      { key: 'C4', duration: '4n', time: '2:0:0' },
      { key: 'D4', duration: '4n', time: '2:1:0' },
      { key: 'E4', duration: '4n', time: '2:2:0' },
      { key: 'F4', duration: '4n', time: '2:3:0' },
      { key: 'G4', duration: '4n', time: '3:0:0' },
      { key: 'G4', duration: '4n', time: '3:1:0' },
      { key: 'A4', duration: '8n', time: '3:2:0' },
      { key: 'G4', duration: '8n', time: '3:2:2' },
      { key: 'F4', duration: '4n', time: '3:3:0' },
      { key: 'E4', duration: '4n', time: '4:0:0' },
      { key: 'D4', duration: '4n', time: '4:1:0' },
      { key: 'C4', duration: '2n', time: '4:2:0' },
    ],
  },
  {
    id: 'bhool-bhulaiyaa',
    title: 'Bhool Bhulaiyaa',
    instrument: 'piano',
    difficulty: 'Intermediate',
    tempo: 130,
    imageId: 'lesson-bhool-bhulaiyaa',
    notes: [
      { key: 'C4', duration: '8n', time: '0:0:0' },
      { key: 'C4', duration: '8n', time: '0:0:2' },
      { key: 'D4', duration: '8n', time: '0:1:0' },
      { key: 'D#4', duration: '8n', time: '0:1:2' },
      { key: 'F4', duration: '4n', time: '0:2:0' },
      { key: 'D#4', duration: '4n', time: '0:3:0' },
      { key: 'C4', duration: '8n', time: '1:0:0' },
      { key: 'C4', duration: '8n', time: '1:0:2' },
      { key: 'D#4', duration: '8n', time: '1:1:0' },
      { key: 'F4', duration: '8n', time: '1:1:2' },
      { key: 'G4', duration: '2n', time: '1:2:0' },
      { key: 'G4', duration: '8n', time: '2:0:0' },
      { key: 'G4', duration: '8n', time: '2:0:2' },
      { key: 'F4', duration: '8n', time: '2:1:0' },
      { key: 'G4', duration: '8n', time: '2:1:2' },
      { key: 'D#4', duration: '4n', time: '2:2:0' },
      { key: 'D#4', duration: '4n', time: '2:3:0' },
      { key: 'F4', duration: '8n', time: '3:0:0' },
      { key: 'D#4', duration: '8n', time: '3:0:2' },
      { key: 'C4', duration: '2n', time: '3:1:0' },
      { key: 'C4', duration: '8n', time: '4:0:0' },
      { key: 'C4', duration: '8n', time: '4:0:2' },
      { key: 'D4', duration: '8n', time: '4:1:0' },
      { key: 'D#4', duration: '8n', time: '4:1:2' },
      { key: 'F4', duration: '2n', time: '4:2:0' },
    ],
  },
  {
    id: 'ode-to-joy',
    title: 'Ode to Joy',
    instrument: 'piano',
    difficulty: 'Beginner',
    tempo: 120,
    imageId: 'lesson-ode-to-joy',
    notes: [
      { key: 'E4', duration: '4n', time: '0:0:0' },
      { key: 'E4', duration: '4n', time: '0:1:0' },
      { key: 'F4', duration: '4n', time: '0:2:0' },
      { key: 'G4', duration: '4n', time: '0:3:0' },
      { key: 'G4', duration: '4n', time: '1:0:0' },
      { key: 'F4', duration: '4n', time: '1:1:0' },
      { key: 'E4', duration: '4n', time: '1:2:0' },
      { key: 'D4', duration: '4n', time: '1:3:0' },
      { key: 'C4', duration: '4n', time: '2:0:0' },
      { key: 'C4', duration: '4n', time: '2:1:0' },
      { key: 'D4', duration: '4n', time: '2:2:0' },
      { key: 'E4', duration: '4n', time: '2:3:0' },
      { key: 'E4', duration: '4.n', time: '3:0:0' },
      { key: 'D4', duration: '8n', time: '3:1:2' },
      { key: 'D4', duration: '2n', time: '3:2:0' },
      { key: 'E4', duration: '4n', time: '4:0:0' },
      { key: 'E4', duration: '4n', time: '4:1:0' },
      { key: 'F4', duration: '4n', time: '4:2:0' },
      { key: 'G4', duration: '4n', time: '4:3:0' },
      { key: 'G4', duration: '4n', time: '5:0:0' },
      { key: 'F4', duration: '4n', time: '5:1:0' },
      { key: 'E4', duration: '4n', time: '5:2:0' },
      { key: 'D4', duration: '4n', time: '5:3:0' },
    ],
  },
  {
    id: 'happy-birthday',
    title: 'Happy Birthday',
    instrument: 'piano',
    difficulty: 'Beginner',
    tempo: 100,
    imageId: 'lesson-happy-birthday',
    notes: [
      { key: 'C4', duration: '8n', time: '0:0:0' },
      { key: 'C4', duration: '8n', time: '0:0:2' },
      { key: 'D4', duration: '4n', time: '0:1:0' },
      { key: 'C4', duration: '4n', time: '0:2:0' },
      { key: 'F4', duration: '4n', time: '0:3:0' },
      { key: 'E4', duration: '2n', time: '1:0:0' },
      { key: 'C4', duration: '8n', time: '2:0:0' },
      { key: 'C4', duration: '8n', time: '2:0:2' },
      { key: 'D4', duration: '4n', time: '2:1:0' },
      { key: 'C4', duration: '4n', time: '2:2:0' },
      { key: 'G4', duration: '4n', time: '2:3:0' },
      { key: 'F4', duration: '2n', time: '3:0:0' },
      { key: 'C4', duration: '8n', time: '4:0:0' },
      { key: 'C4', duration: '8n', time: '4:0:2' },
      { key: 'C5', duration: '4n', time: '4:1:0' },
      { key: 'A4', duration: '4n', time: '4:2:0' },
      { key: 'F4', duration: '4n', time: '4:3:0' },
      { key: 'E4', duration: '4n', time: '5:0:0' },
      { key: 'D4', duration: '2n', time: '5:1:0' },
    ],
  },
  {
    id: 'fur-elise',
    title: 'Für Elise',
    instrument: 'piano',
    difficulty: 'Advanced',
    tempo: 125,
    imageId: 'lesson-fur-elise',
    notes: [
      { key: 'E5', duration: '8n', time: '0:0:0' },
      { key: 'D#5', duration: '8n', time: '0:0:2' },
      { key: 'E5', duration: '8n', time: '0:1:0' },
      { key: 'D#5', duration: '8n', time: '0:1:2' },
      { key: 'E5', duration: '8n', time: '0:2:0' },
      { key: 'B4', duration: '8n', time: '0:2:2' },
      { key: 'D5', duration: '8n', time: '0:3:0' },
      { key: 'C5', duration: '8n', time: '0:3:2' },
      { key: 'A4', duration: '4n', time: '1:0:0' },
      { key: 'C4', duration: '8n', time: '1:1:0' },
      { key: 'E4', duration: '8n', time: '1:1:2' },
      { key: 'A4', duration: '4n', time: '1:2:0' },
      { key: 'B4', duration: '4n', time: '1:3:0' },
      { key: 'E4', duration: '8n', time: '2:0:0' },
      { key: 'G#4', duration: '8n', time: '2:0:2' },
      { key: 'B4', duration: '4n', time: '2:1:0' },
      { key: 'C5', duration: '4n', time: '2:2:0' },
      { key: 'E5', duration: '8n', time: '3:0:0' },
      { key: 'D#5', duration: '8n', time: '3:0:2' },
      { key: 'E5', duration: '8n', time: '3:1:0' },
      { key: 'D#5', duration: '8n', time: '3:1:2' },
      { key: 'E5', duration: '8n', time: '3:2:0' },
      { key: 'B4', duration: '8n', time: '3:2:2' },
      { key: 'D5', duration: '8n', time: '3:3:0' },
      { key: 'C5', duration: '8n', time: '3:3:2' },
      { key: 'A4', duration: '4n', time: '4:0:0' },
    ],
  },
  {
    id: 'shape-of-you',
    title: 'Shape of You',
    instrument: 'piano',
    difficulty: 'Intermediate',
    tempo: 96,
    imageId: 'lesson-shape-of-you',
    notes: [
      { key: 'C#4', duration: '8n', time: '0:0:0' },
      { key: 'E4', duration: '8n', time: '0:0:2' },
      { key: 'C#4', duration: '8n', time: '0:1:0' },
      { key: 'C#4', duration: '8n', time: '0:1:2' },
      { key: 'E4', duration: '8n', time: '0:2:0' },
      { key: 'C#4', duration: '8n', time: '0:2:2' },
      { key: 'D#4', duration: '4n', time: '0:3:0' },
      { key: 'B3', duration: '4n', time: '0:3:2' },
      { key: 'C#4', duration: '8n', time: '1:0:0' },
      { key: 'E4', duration: '8n', time: '1:0:2' },
      { key: 'C#4', duration: '8n', time: '1:1:0' },
      { key: 'C#4', duration: '8n', time: '1:1:2' },
      { key: 'E4', duration: '8n', time: '1:2:0' },
      { key: 'C#4', duration: '8n', time: '1:2:2' },
      { key: 'D#4', duration: '4n', time: '1:3:0' },
      { key: 'B3', duration: '4n', time: '1:3:2' },
      { key: 'C#4', duration: '8n', time: '2:0:0' },
      { key: 'E4', duration: '8n', time: '2:0:2' },
      { key: 'C#4', duration: '8n', time: '2:1:0' },
      { key: 'C#4', duration: '8n', time: '2:1:2' },
      { key: 'E4', duration: '8n', time: '2:2:0' },
      { key: 'C#4', duration: '8n', time: '2:2:2' },
      { key: 'D#4', duration: '4n', time: '2:3:0' },
    ],
  },
  {
    id: 'sargam-practice',
    title: 'Sargam Practice',
    instrument: 'piano',
    difficulty: 'Beginner',
    tempo: 100,
    imageId: 'lesson-sargam',
    notes: [
      { key: 'C4', duration: '4n', time: '0:0:0' },
      { key: 'D4', duration: '4n', time: '0:1:0' },
      { key: 'E4', duration: '4n', time: '0:2:0' },
      { key: 'F4', duration: '4n', time: '0:3:0' },
      { key: 'G4', duration: '4n', time: '1:0:0' },
      { key: 'A4', duration: '4n', time: '1:1:0' },
      { key: 'B4', duration: '4n', time: '1:2:0' },
      { key: 'C5', duration: '4n', time: '1:3:0' },
      { key: 'C5', duration: '4n', time: '2:0:0' },
      { key: 'B4', duration: '4n', time: '2:1:0' },
      { key: 'A4', duration: '4n', time: '2:2:0' },
      { key: 'G4', duration: '4n', time: '2:3:0' },
      { key: 'F4', duration: '4n', time: '3:0:0' },
      { key: 'E4', duration: '4n', time: '3:1:0' },
      { key: 'D4', duration: '4n', time: '3:2:0' },
      { key: 'C4', duration: '4n', time: '3:3:0' },
      { key: 'C4', duration: '4n', time: '4:0:0' },
      { key: 'E4', duration: '4n', time: '4:1:0' },
      { key: 'G4', duration: '4n', time: '4:2:0' },
      { key: 'C5', duration: '2n', time: '4:3:0' },
    ],
  },
];
