import type { Lesson } from '@/types';

export const lessons: Lesson[] = [
  {
    id: 'twinkle-twinkle',
    title: 'Twinkle Twinkle Little Star',
    instrument: 'piano',
    difficulty: 'Beginner',
    tempo: 100,
    imageId: 'piano-lesson',
    notes: [
      { key: 'C4', duration: '4n', time: 0 },
      { key: 'C4', duration: '4n', time: 0.5 },
      { key: 'G4', duration: '4n', time: 1 },
      { key: 'G4', duration: '4n', time: 1.5 },
      { key: 'A4', duration: '4n', time: 2 },
      { key: 'A4', duration: '4n', time: 2.5 },
      { key: 'G4', duration: '2n', time: 3 },
      { key: 'F4', duration: '4n', time: 4 },
      { key: 'F4', duration: '4n', time: 4.5 },
      { key: 'E4', duration: '4n', time: 5 },
      { key: 'E4', duration: '4n', time: 5.5 },
      { key: 'D4', duration: '4n', time: 6 },
      { key: 'D4', duration: '4n', time: 6.5 },
      { key: 'C4', duration: '2n', time: 7 },
    ],
  },
  {
    id: 'ode-to-joy',
    title: 'Ode to Joy',
    instrument: 'piano',
    difficulty: 'Beginner',
    tempo: 120,
    imageId: 'piano-lesson',
    notes: [
        { key: 'E4', duration: '4n', time: 0 },
        { key: 'E4', duration: '4n', time: 0.5 },
        { key: 'F4', duration: '4n', time: 1 },
        { key: 'G4', duration: '4n', time: 1.5 },
        { key: 'G4', duration: '4n', time: 2 },
        { key: 'F4', duration: '4n', time: 2.5 },
        { key: 'E4', duration: '4n', time: 3 },
        { key: 'D4', duration: '4n', time: 3.5 },
        { key: 'C4', duration: '4n', time: 4 },
        { key: 'C4', duration: '4n', time: 4.5 },
        { key: 'D4', duration: '4n', time: 5 },
        { key: 'E4', duration: '4n', time: 5.5 },
        { key: 'E4', duration: '2n', time: 6 },
        { key: 'D4', duration: '4n', time: 6.5 },
        { key: 'D4', duration: '2n', time: 7 },
    ],
  },
  {
    id: 'jana-gana-mana',
    title: 'Jana Gana Mana',
    instrument: 'piano',
    difficulty: 'Intermediate',
    tempo: 104,
    imageId: 'piano-lesson',
    notes: [
      { key: 'C4', duration: '8n', time: 0 },
      { key: 'D4', duration: '8n', time: 0.5 },
      { key: 'E4', duration: '4n', time: 1 },
      { key: 'E4', duration: '4n', time: 1.5 },
      { key: 'E4', duration: '4n', time: 2 },
      { key: 'E4', duration: '8n', time: 2.5 },
      { key: 'D4', duration: '8n', time: 3 },
      { key: 'C#4', duration: '4n', time: 3.5 },
      { key: 'D4', duration: '4n', time: 4 },
      { key: 'E4', duration: '2n', time: 4.5 },
      { key: 'D4', duration: '4n', time: 5.5 },
      { key: 'D4', duration: '2n', time: 6 },
      { key: 'G4', duration: '4n', time: 7 },
      { key: 'F#4', duration: '4n', time: 7.5 },
      { key: 'E4', duration: '4n', time: 8 },
      { key: 'D4', duration: '4n', time: 8.5 },
      { key: 'C4', duration: '2n', time: 9 },
    ],
  },
  {
    id: 'basic-rock-beat',
    title: 'Basic Rock Beat',
    instrument: 'drums',
    difficulty: 'Beginner',
    tempo: 90,
    imageId: 'drums-lesson',
    notes: [
      { key: 'C4', duration: '4n', time: 0 }, // Kick
      { key: 'E4', duration: '4n', time: 0.5 }, // Snare
      { key: 'C4', duration: '4n', time: 1 }, // Kick
      { key: 'E4', duration: '4n', time: 1.5 }, // Snare
    ],
  },
  {
    id: 'smoke-on-the-water-riff',
    title: 'Smoke on the Water Riff',
    instrument: 'guitar',
    difficulty: 'Intermediate',
    tempo: 115,
    imageId: 'guitar-lesson',
    notes: [
        { key: 'D4', duration: '4n', time: 0 },
        { key: 'F4', duration: '4n', time: 0.5 },
        { key: 'G4', duration: '2n', time: 1 },
        { key: 'D4', duration: '4n', time: 2 },
        { key: 'F4', duration: '4n', time: 2.5 },
        { key: 'G#4', duration: '4n', time: 3 },
        { key: 'G4', duration: '2n', time: 3.5 },
    ],
  },
  {
    id: 'violin-scales',
    title: 'Major Scale Practice',
    instrument: 'violin',
    difficulty: 'Beginner',
    tempo: 80,
    imageId: 'violin-lesson',
    notes: [
        { key: 'G3', duration: '4n', time: 0 },
        { key: 'A3', duration: '4n', time: 0.5 },
        { key: 'B3', duration: '4n', time: 1 },
        { key: 'C4', duration: '4n', time: 1.5 },
        { key: 'D4', duration: '4n', time: 2 },
        { key: 'E4', duration: '4n', time: 2.5 },
        { key: 'F#4', duration: '4n', time: 3 },
        { key: 'G4', duration: '2n', time: 3.5 },
    ],
  },
];
