'use client';

import { useState, useMemo } from 'react';
import { 
    useFirestore, 
    useCollection, 
    useMemoFirebase,
    updateDocumentNonBlocking
} from '@/firebase';
import { collection, query, orderBy, limit, doc, collectionGroup } from 'firebase/firestore';
import { 
    Users, 
    Zap, 
    ShieldCheck, 
    Search, 
    Edit, 
    Music,
    Settings2,
    Check,
    TrendingUp,
    Activity,
    Clock,
    UserCircle,
    ArrowRight
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { useToast } from '@/hooks/use-toast';
import type { UserProfile } from '@/types';
import { cn } from '@/lib/utils';

export default function AdminDashboard() {
    const firestore = useFirestore();
    const { toast } = useToast();
    const [searchTerm, setSearchTerm] = useState('');
    const [editingUserId, setEditingUserId] = useState<string | null>(null);
    const [creditDelta, setCreditDelta] = useState<string>('0');

    // Fetch all users
    const usersQuery = useMemoFirebase(() => {
        if (!firestore) return null;
        return query(collection(firestore, 'users'), orderBy('createdAt', 'desc'), limit(100));
    }, [firestore]);
    const { data: users, isLoading: usersLoading } = useCollection<UserProfile>(usersQuery);

    // Fetch global activity (all melodies generated by any user)
    const activityQuery = useMemoFirebase(() => {
        if (!firestore) return null;
        return query(collectionGroup(firestore, 'generatedMelodies'), orderBy('createdAt', 'desc'), limit(20));
    }, [firestore]);
    const { data: globalActivity, isLoading: activityLoading } = useCollection(activityQuery);

    const filteredUsers = useMemo(() => {
        if (!users) return [];
        return users.filter(u => 
            u.displayName?.toLowerCase().includes(searchTerm.toLowerCase()) || 
            u.email?.toLowerCase().includes(searchTerm.toLowerCase()) ||
            u.id.includes(searchTerm)
        );
    }, [users, searchTerm]);

    const stats = useMemo(() => {
        if (!users) return { totalUsers: 0, totalCredits: 0, proUsers: 0, creatorUsers: 0 };
        return {
            totalUsers: users.length,
            totalCredits: users.reduce((acc, u) => acc + (u.credits || 0), 0),
            proUsers: users.filter(u => u.plan === 'pro').length,
            creatorUsers: users.filter(u => u.plan === 'creator').length
        };
    }, [users]);

    const handleUpdateCredits = (userId: string, currentCredits: number) => {
        if (!firestore) return;
        const delta = parseInt(creditDelta);
        if (isNaN(delta)) {
            toast({ title: "Invalid Amount", variant: "destructive" });
            return;
        }

        const userRef = doc(firestore, 'users', userId);
        updateDocumentNonBlocking(userRef, { 
            credits: Math.max(0, currentCredits + delta) 
        });
        
        toast({ title: "Credits Updated", description: `${delta > 0 ? '+' : ''}${delta} credits applied.` });
        setEditingUserId(null);
        setCreditDelta('0');
    };

    const handleUpdatePlan = (userId: string, newPlan: string) => {
        if (!firestore) return;
        const userRef = doc(firestore, 'users', userId);
        updateDocumentNonBlocking(userRef, { plan: newPlan });
        toast({ title: "Plan Updated", description: `User switched to ${newPlan} plan.` });
    };

    return (
        <div className="space-y-10 pb-32 max-w-7xl mx-auto">
            {/* Stats Overview */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                <Card className="bg-primary/5 border-primary/10 rounded-3xl">
                    <CardHeader className="pb-2">
                        <CardDescription className="text-[10px] font-black uppercase tracking-widest text-primary">Registered Users</CardDescription>
                        <CardTitle className="text-3xl font-bold flex items-center gap-3">
                            <Users className="h-5 w-5 text-primary" />
                            {stats.totalUsers}
                        </CardTitle>
                    </CardHeader>
                </Card>
                <Card className="bg-secondary/5 border-secondary/10 rounded-3xl">
                    <CardHeader className="pb-2">
                        <CardDescription className="text-[10px] font-black uppercase tracking-widest text-secondary">Neural Liquidity</CardDescription>
                        <CardTitle className="text-3xl font-bold flex items-center gap-3">
                            <Zap className="h-5 w-5 text-secondary" />
                            {Math.floor(stats.totalCredits)}
                        </CardTitle>
                    </CardHeader>
                </Card>
                <Card className="bg-accent/5 border-accent/10 rounded-3xl">
                    <CardHeader className="pb-2">
                        <CardDescription className="text-[10px] font-black uppercase tracking-widest text-accent">Pro Members</CardDescription>
                        <CardTitle className="text-3xl font-bold flex items-center gap-3">
                            <ShieldCheck className="h-5 w-5 text-accent" />
                            {stats.proUsers}
                        </CardTitle>
                    </CardHeader>
                </Card>
                <Card className="bg-muted/5 border-border/50 rounded-3xl">
                    <CardHeader className="pb-2">
                        <CardDescription className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">Creator Network</CardDescription>
                        <CardTitle className="text-3xl font-bold flex items-center gap-3">
                            <TrendingUp className="h-5 w-5 text-muted-foreground" />
                            {stats.creatorUsers}
                        </CardTitle>
                    </CardHeader>
                </Card>
            </div>

            <Tabs defaultValue="users" className="space-y-8">
                <TabsList className="bg-muted/50 p-1 rounded-2xl h-auto border border-border/50">
                    <TabsTrigger value="users" className="rounded-xl px-8 py-2.5 font-bold data-[state=active]:bg-background">User Registry</TabsTrigger>
                    <TabsTrigger value="activity" className="rounded-xl px-8 py-2.5 font-bold data-[state=active]:bg-background">Live Activity</TabsTrigger>
                </TabsList>

                <TabsContent value="users" className="space-y-6 animate-in slide-in-from-bottom-4 duration-500">
                    <div className="flex items-center gap-4 max-w-md">
                        <div className="relative flex-1">
                            <Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                            <Input 
                                placeholder="Search Name, Email, or UID..." 
                                className="pl-10 rounded-xl bg-muted/20 border-primary/10"
                                value={searchTerm}
                                onChange={(e) => setSearchTerm(e.target.value)}
                            />
                        </div>
                    </div>

                    <div className="grid gap-4">
                        {filteredUsers.map(u => (
                            <Card key={u.id} className="border-primary/5 hover:border-primary/20 transition-all bg-card/50 overflow-hidden rounded-[1.5rem]">
                                <CardContent className="p-0">
                                    <div className="flex flex-col md:flex-row md:items-center p-6 gap-6">
                                        <div className="flex items-center gap-4 flex-1 min-w-0">
                                            <Avatar className="h-12 w-12 border-2 border-primary/10 shadow-lg shadow-black/20">
                                                <AvatarImage src={u.avatarUrl || ''} />
                                                <AvatarFallback>{u.displayName?.[0] || 'U'}</AvatarFallback>
                                            </Avatar>
                                            <div className="truncate">
                                                <h3 className="font-bold text-lg truncate flex items-center gap-2">
                                                    {u.displayName}
                                                    {u.plan !== 'free' && <ShieldCheck className="h-3 w-3 text-primary" />}
                                                </h3>
                                                <p className="text-xs text-muted-foreground truncate">{u.email}</p>
                                                <p className="text-[8px] font-mono text-muted-foreground/50 truncate mt-1">UID: {u.id}</p>
                                            </div>
                                        </div>

                                        <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 md:items-center">
                                            <div className="space-y-1">
                                                <p className="text-[9px] font-black uppercase tracking-widest text-muted-foreground">Neural Level</p>
                                                <div className="flex gap-1">
                                                    {['free', 'creator', 'pro'].map(p => (
                                                        <Button 
                                                            key={p} 
                                                            variant="ghost" 
                                                            size="sm" 
                                                            onClick={() => handleUpdatePlan(u.id, p)}
                                                            className={cn(
                                                                "h-6 px-2 text-[9px] uppercase font-black rounded-md",
                                                                u.plan === p ? "bg-primary/20 text-primary border border-primary/20" : "text-muted-foreground opacity-50"
                                                            )}
                                                        >
                                                            {p}
                                                        </Button>
                                                    ))}
                                                </div>
                                            </div>

                                            <div className="space-y-1">
                                                <p className="text-[9px] font-black uppercase tracking-widest text-muted-foreground">Credits</p>
                                                {editingUserId === u.id ? (
                                                    <div className="flex items-center gap-2 animate-in zoom-in-95">
                                                        <Input 
                                                            type="number" 
                                                            value={creditDelta} 
                                                            onChange={(e) => setCreditDelta(e.target.value)}
                                                            className="h-8 w-20 bg-muted/50 border-primary/20 text-xs text-center font-bold"
                                                        />
                                                        <Button size="icon" className="h-8 w-8 rounded-lg" onClick={() => handleUpdateCredits(u.id, u.credits || 0)}>
                                                            <Check className="h-4 w-4" />
                                                        </Button>
                                                    </div>
                                                ) : (
                                                    <div className="flex items-center gap-2">
                                                        <span className="font-bold text-primary text-md">{u.credits ?? 0}</span>
                                                        <Button variant="ghost" size="icon" className="h-6 w-6 rounded-md opacity-50 hover:opacity-100 transition-opacity" onClick={() => {
                                                            setEditingUserId(u.id);
                                                            setCreditDelta('0');
                                                        }}>
                                                            <Edit className="h-3 w-3" />
                                                        </Button>
                                                    </div>
                                                )}
                                            </div>

                                            <div className="hidden sm:block space-y-1">
                                                <p className="text-[9px] font-black uppercase tracking-widest text-muted-foreground">Onboarding</p>
                                                <p className="text-[10px] text-muted-foreground">{u.createdAt ? new Date(u.createdAt.toDate()).toLocaleDateString() : 'N/A'}</p>
                                            </div>
                                        </div>
                                    </div>
                                </CardContent>
                            </Card>
                        ))}
                    </div>
                </TabsContent>

                <TabsContent value="activity" className="animate-in slide-in-from-bottom-4 duration-500">
                    <div className="grid gap-4">
                        {globalActivity && globalActivity.length > 0 ? (
                            globalActivity.map((act: any) => (
                                <Card key={act.id} className="border-primary/5 bg-card/30 rounded-2xl overflow-hidden group hover:border-primary/20 transition-all">
                                    <CardContent className="p-4">
                                        <div className="flex items-center justify-between">
                                            <div className="flex items-center gap-4">
                                                <div className="h-10 w-10 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
                                                    {act.generationContext === 'Melody Maker' ? <Music className="h-5 w-5 text-primary" /> : <Activity className="h-5 w-5 text-secondary" />}
                                                </div>
                                                <div>
                                                    <div className="flex items-center gap-2">
                                                        <h4 className="font-bold text-sm">{act.title}</h4>
                                                        <span className="text-[8px] font-black uppercase tracking-widest bg-muted px-1.5 py-0.5 rounded text-muted-foreground">
                                                            {act.generationContext}
                                                        </span>
                                                    </div>
                                                    <p className="text-[10px] text-muted-foreground flex items-center gap-1 mt-0.5">
                                                        <UserCircle className="h-2.5 w-2.5" /> {act.userId}
                                                    </p>
                                                </div>
                                            </div>
                                            <div className="text-right">
                                                <div className="flex items-center gap-1 text-[10px] text-muted-foreground mb-1">
                                                    <Clock className="h-3 w-3" />
                                                    {act.createdAt ? new Date(act.createdAt.toDate()).toLocaleTimeString() : 'Just now'}
                                                </div>
                                                <div className="text-[9px] font-mono text-primary/60 truncate max-w-[150px]">
                                                    {act.notes?.length || 0} notes synthesized
                                                </div>
                                            </div>
                                        </div>
                                    </CardContent>
                                </Card>
                            ))
                        ) : (
                            <div className="py-20 text-center space-y-4 border-2 border-dashed border-primary/5 rounded-[2rem]">
                                <Activity className="h-12 w-12 text-primary mx-auto opacity-20 animate-pulse" />
                                <p className="text-sm text-muted-foreground italic">Neural network is quiet. No global activity detected recently.</p>
                            </div>
                        )}
                    </div>
                </TabsContent>
            </Tabs>
        </div>
    );
}